"""Declarative architecture rules for the current repository shape."""

from __future__ import annotations

from .rules import AbsentPathRule, ForbiddenPatternRule, ForbiddenReferenceRule, RequiredPatternRule


def _absent(rule_id: str, path: str, message: str = "obsolete path remains") -> AbsentPathRule:
    return AbsentPathRule(rule_id, path, message)


def _forbid(rule_id: str, path: str, pattern: str, message: str) -> ForbiddenPatternRule:
    return ForbiddenPatternRule(rule_id, path, pattern, message)


ABSENT_PATH_RULES = (
    _absent("frontend-legacy-e2e-root", "frontend/e2e"),
    _absent("frontend-misclassified-event-order-e2e", "frontend/tests/e2e/env/event-order.spec.ts"),
    _absent("frontend-environment-domain-mirror", "frontend/src/types/domain/env.ts"),
    _absent("frontend-capability-domain-mirror", "frontend/src/types/domain/capability.ts"),
    _absent("frontend-workflow-domain-mirror", "frontend/src/types/domain/workflow.ts"),
    _absent("frontend-environment-normalize", "frontend/src/services/env/normalize.ts"),
    _absent("frontend-environment-normalize-test", "frontend/tests/unit/services/env/normalize.spec.ts"),
    _absent("frontend-backend-support-generated", "frontend/src/types/generated/BackendDeviceSupport.ts"),
    _absent("frontend-ipc-barrel", "frontend/src/lib/ipc/index.ts"),
    _absent("frontend-model-metrics-barrel", "frontend/src/services/model-metrics.ts"),
    _absent("frontend-preset-select-option-type", "frontend/src/services/preset/select-options.ts"),
    _absent("frontend-enhance-rules-barrel", "frontend/src/services/preset/enhance-rules.ts"),
    _absent("frontend-enhance-field-aggregator", "frontend/src/composables/forms/enhance-field-bindings.ts"),
    _absent("frontend-enhance-field-aggregator-test", "frontend/src/composables/forms/enhance-field-bindings.spec.ts"),
    _absent("frontend-encode-output-aggregator", "frontend/src/composables/forms/encode-output-bindings.ts"),
    _absent("frontend-enhance-option-aggregator", "frontend/src/composables/forms/enhance-option-bindings.ts"),
    _absent("frontend-decode-form-aggregator", "frontend/src/composables/forms/decode-form-bindings.ts"),
    _absent(
        "frontend-decode-form-aggregator-test",
        "frontend/tests/unit/composables/forms/decode-form-bindings.spec.ts",
    ),
    _absent(
        "frontend-enhance-option-aggregator-test",
        "frontend/src/composables/forms/enhance-option-bindings.spec.ts",
    ),
    _absent("backend-tensor-chain", "backend/app/processing/streaming/_tensor_chain.py"),
    _absent("backend-tensor-chain-test", "backend/tests/test_processing/test_tensor_chain.py"),
    _absent("backend-raw-runtime", "backend/app/processing/streaming/pipeline_raw_runtime.py"),
    _absent("backend-raw-state", "backend/app/processing/streaming/pipeline_raw_state.py"),
    _absent("backend-raw-stage", "backend/app/processing/streaming/pipeline_raw_stage.py"),
    _absent("backend-raw-completion", "backend/app/processing/streaming/pipeline_raw_completion.py"),
    _absent("backend-worker-pipeline-queue", "backend/app/processing/streaming/worker_pipeline_queue.py"),
    _absent("backend-raw-runtime-test", "backend/tests/test_processing/test_pipeline_raw_runtime.py"),
    _absent("backend-raw-state-test", "backend/tests/test_processing/test_pipeline_raw_state.py"),
    _absent("backend-raw-stage-test", "backend/tests/test_processing/test_pipeline_raw_stage.py"),
    _absent("backend-raw-completion-test", "backend/tests/test_processing/test_pipeline_raw_completion.py"),
    _absent("backend-worker-pipeline-queue-test", "backend/tests/test_processing/test_worker_pipeline_queue.py"),
    _absent(
        "backend-stage-file-chunk-progress",
        "backend/app/processing/streaming/stage_file_chunk_progress.py",
    ),
    _absent(
        "backend-stage-file-chunk-progress-test",
        "backend/tests/test_processing/test_stage_file_chunk_progress.py",
    ),
    _absent(
        "backend-stage-file-rules-forwarder",
        "backend/app/processing/streaming/stage_file_rules.py",
    ),
    _absent(
        "backend-stage-file-rules-forwarder-test",
        "backend/tests/test_processing/test_stage_file_rules.py",
    ),
    _absent("backend-streaming-decoder", "backend/app/processing/streaming/decoder.py"),
    _absent("backend-metrics-view-interface", "backend/app/protocol/metrics_view.py"),
    _absent("backend-streaming-encoder", "backend/app/processing/streaming/encoder.py"),
    _absent("backend-streaming-processor", "backend/app/processing/streaming/processor.py"),
    _absent("backend-processor-algorithms", "backend/app/processing/streaming/processor_algorithms.py"),
    _absent("backend-processor-stage-execution", "backend/app/processing/streaming/processor_stage_execution.py"),
    _absent("backend-processor-streams", "backend/app/processing/streaming/processor_streams.py"),
    _absent("backend-processor-stream-io", "backend/app/processing/streaming/processor_stream_io.py"),
    _absent("backend-processor-stream-single", "backend/app/processing/streaming/processor_stream_single.py"),
    _absent(
        "backend-processor-stream-interpolated", "backend/app/processing/streaming/processor_stream_interpolated.py"
    ),
    _absent("backend-processor-stream-sequence", "backend/app/processing/streaming/processor_stream_sequence.py"),
    _absent(
        "paddlegan-vendor-logger",
        "backend/app/algorithms/paddle/paddlegan_vsr/vendor/ppgan/utils/logger.py",
    ),
    _absent("backend-anime-optimization", "backend/app/processing/anime_optimization.py"),
    _absent("backend-anime-optimization-test", "backend/tests/test_processing/test_anime_optimization.py"),
    _absent("frontend-anime-config-type", "frontend/src/types/generated/AnimeConfig.ts"),
    _absent("frontend-anime-config-schema", "frontend/src-tauri/schemas/anime_config.schema.json"),
    _absent("frontend-legacy-anime-e2e", "frontend/tests/e2e/enhance/enhance-anime.spec.ts"),
    _absent("frontend-preprocess-view-forwarder", "frontend/src/views/PreprocessModuleView.vue"),
    _absent("frontend-postprocess-view-forwarder", "frontend/src/views/PostprocessModuleView.vue"),
    _absent("frontend-container-constants", "frontend/src/config/constants.ts"),
    _absent("frontend-gpu-label-constants", "frontend/src/config/gpu-labels.ts"),
    _absent(
        "frontend-gpu-capability-selector-forwarder",
        "frontend/src/composables/selectors/useGpuCapabilities.ts",
    ),
    _absent("frontend-encode-output-state", "frontend/src/composables/forms/encode-output-state.ts"),
    _absent(
        "frontend-encode-output-state-test",
        "frontend/tests/unit/composables/forms/encode-output-state.spec.ts",
    ),
    _absent("frontend-filter-crop-component", "frontend/src/components/filter-steps/FilterCrop.vue"),
    _absent("frontend-filter-pad-component", "frontend/src/components/filter-steps/FilterPad.vue"),
    _absent("frontend-filter-sharpen-component", "frontend/src/components/filter-steps/FilterSharpen.vue"),
    _absent("frontend-filter-denoise-component", "frontend/src/components/filter-steps/FilterDenoise.vue"),
    _absent("frontend-filter-color-component", "frontend/src/components/filter-steps/FilterColor.vue"),
    _absent("backend-algorithm-factory", "backend/app/algorithms/factory.py"),
    _absent("backend-algorithm-factory-test", "backend/tests/test_algorithms/test_factory.py"),
    _absent("backend-ffmpeg-monolithic-probe", "backend/app/utils/ffmpeg/probe.py"),
    _absent("backend-legacy-processing-pipeline", "backend/app/processing/pipeline.py"),
    _absent("backend-legacy-processing-decoder", "backend/app/processing/decoder.py"),
    _absent("backend-legacy-processing-encoder", "backend/app/processing/encoder.py"),
    _absent("backend-legacy-frame-processor", "backend/app/processing/frame_processor.py"),
)


FORBIDDEN_PATTERN_RULES = (
    ForbiddenReferenceRule(
        "frontend-obsolete-option-event-coercion",
        roots=("frontend/src",),
        patterns=(r"\bcoerceOptionValue\b",),
        message="obsolete capability option event coercion",
        suffixes=(".ts", ".tsx", ".vue"),
    ),
    ForbiddenReferenceRule(
        "obsolete-e2e-task-glob",
        roots=(".github/workflows",),
        patterns=(r"[\"']\./e2e/task/\*\*/\*\.spec\.ts[\"']",),
        message="obsolete E2E task glob",
        suffixes=(".yml", ".yaml"),
    ),
    _forbid(
        "e2e-coverage-wrong-root",
        "frontend/tests/e2e/fixtures.ts",
        r"\bfrontendRoot\b|fileURLToPath\s*\(",
        "E2E coverage output is not rooted at the frontend working directory",
    ),
    RequiredPatternRule(
        "e2e-coverage-working-directory",
        "frontend/tests/e2e/fixtures.ts",
        r"resolve\s*\(\s*process\.cwd\(\)\s*,\s*[\"']\.nyc_output[\"']\s*\)",
        "E2E coverage must be written under frontend/.nyc_output",
    ),
    _forbid(
        "encode-form-profile-forwarding",
        "frontend/src/composables/forms/encode-form-bindings.ts",
        r"\.\.\.profile\b|\bcoerceOptionValue\b",
        "encode form exposes an internal profile or option conversion detail",
    ),
    _forbid(
        "enhance-form-internal-forwarding",
        "frontend/src/composables/forms/enhance-form-bindings.ts",
        r"\.\.\.(?:algorithmBindings|viewBindings)\b|return\s+reactive\s*\(\s*\{[\s\S]{0,3000}\b(?:currentSuperResolutionAlgorithm|effectiveSuperResolutionNumFrames|superResolutionModelDetails|currentSuperResolutionModelDetail|currentSuperResolutionRuntimeDetail|superResolutionRuntimeEstimate)\s*[:,]",
        "enhance form exposes an internal super-resolution projection",
    ),
    _forbid(
        "enhance-view-model-internal-output",
        "frontend/src/services/preset/enhance-view-model.ts",
        r"^  (?:superResolutionModelDetails|currentSuperResolutionModelDetail|currentSuperResolutionRuntimeDetail|superResolutionRuntimeFrameCount|superResolutionRuntimeEstimate)\s*:|\.\.\.(?:modelSelection|runtimeView)\b",
        "enhance view-model exposes an internal super-resolution calculation",
    ),
    _forbid(
        "enhance-model-selection-dead-output",
        "frontend/src/services/preset/enhance-model-selection.ts",
        r"interface\s+EnhanceModelSelection\s*\{[\s\S]{0,1000}\b(?:superResolutionModelDetails|currentSuperResolutionModelDetail)\s*:|return\s*\{[\s\S]{0,800}\b(?:superResolutionModelDetails|currentSuperResolutionModelDetail)\s*,",
        "enhance model selection exposes a test-only super-resolution intermediate",
    ),
    _forbid(
        "enhance-runtime-view-dead-output",
        "frontend/src/services/preset/enhance-runtime-view.ts",
        r"interface\s+EnhanceRuntimeView\s*\{[\s\S]{0,1000}\bsuperResolutionRuntimeEstimate\s*:|\.\.\.estimates\b",
        "enhance runtime view exposes an internal super-resolution estimate",
    ),
    ForbiddenReferenceRule(
        "obsolete-backend-internal-symbols",
        roots=("backend/app",),
        patterns=(
            r"\bget_cuda_device_count\b",
            r"\bget_onnx_model_dir\b",
            r"\bemit_error\b",
            r"\bcollect_config_sections\b",
            r"\bread_completed_segments\b",
            r"\bsuper_resolution_changes_dimensions\b",
            r"\bis_paddlegan_vsr_step\b",
            r"\bentry_needs_sequence\b",
            r"\bget_cached_backend\b",
            r"\bshould_prefer_tensor_stage\b",
            r"\bAlgorithmFactoryFn\b",
            r"\bBackendFactoryFn\b",
            r"\bread_declared_frames\b",
            r"\b_check_(?:pytorch|paddle|onnxruntime)_in_subprocess\b",
        ),
        message="obsolete backend internal symbol",
        suffixes=(".py",),
    ),
    ForbiddenReferenceRule(
        "obsolete-algorithm-registry",
        roots=("backend/app", "backend/tests"),
        patterns=(r"\bAlgorithmFactory\b", r"app\.algorithms\.factory"),
        message="obsolete global algorithm registry",
        suffixes=(".py",),
    ),
    ForbiddenReferenceRule(
        "obsolete-direct-decoded-writer",
        roots=("backend/app", "backend/tests"),
        patterns=(r"\bwrite_decoded_frames_to_worker\b",),
        message="test-only decoded writer target",
        suffixes=(".py",),
    ),
    ForbiddenReferenceRule(
        "obsolete-filter-helpers",
        roots=("frontend/src",),
        patterns=(r"\bcreateFilterParamsPatch\b", r"\bfilterLabel\b"),
        message="obsolete filter helper export",
        suffixes=(".ts", ".vue"),
    ),
    _forbid(
        "stage-runtime-rule-reexport",
        "backend/app/processing/streaming/stage_runtime.py",
        r"\balgorithm_kwargs_for_create\b",
        "stage rule re-export from runtime",
    ),
    _forbid(
        "stage-worker-factory-public-details",
        "backend/app/processing/streaming/stage_worker_factory.py",
        r"^\s*(?:def\s+(?:register_single_algorithm|backend_name)\b|AlgorithmFactory(?:Fn)?\s*=|BackendFactoryFn\s*=)|\bAlgorithmFactory\b|\.register\s*\(",
        "public stage-worker factory implementation detail",
    ),
    RequiredPatternRule(
        "stage-worker-factory-public-api",
        "backend/app/processing/streaming/stage_worker_factory.py",
        r"__all__\s*=\s*\[\s*[\"']create_algorithm[\"']\s*,\s*[\"']create_backend[\"']\s*,?\s*\]",
        "stage-worker factory must expose only create_algorithm/create_backend",
    ),
    _forbid(
        "worker-processes-public-backend-dir",
        "backend/app/processing/streaming/worker_processes.py",
        r"^\s*def\s+backend_dir\b",
        "public worker-process backend directory helper",
    ),
    _forbid(
        "worker-processes-public-lifecycle-helpers",
        "backend/app/processing/streaming/worker_processes.py",
        r"^def\s+(?:spawn_stage_workers|wait_for_workers)\b|__all__\s*=\s*\[[\s\S]{0,300}[\"'](?:spawn_stage_workers|wait_for_workers)[\"']",
        "worker lifecycle helper exposed outside stage_worker_session",
    ),
    _forbid(
        "stage-plan-dead-fields",
        "backend/app/planning/stage_plan.py",
        r"^\s+(?:total_output_frames|total_pairs)\s*:",
        "dead StagePlan field",
    ),
    _forbid(
        "rust-obsolete-environment-fields",
        "frontend/src-tauri/src/models/env.rs",
        r"\bBackendDeviceSupport\b|\b(?:sequence_mode|device_type|driver_version|adapter_compatibility)\s*:",
        "obsolete Rust environment protocol field",
    ),
    _forbid(
        "rust-public-internal-root-modules",
        "frontend/src-tauri/src/lib.rs",
        r"^pub\s+mod\s+(?:error|protocol)\s*;",
        "crate-internal Rust root module is public",
    ),
    _forbid(
        "rust-public-environment-model-module",
        "frontend/src-tauri/src/models/mod.rs",
        r"^pub\s+mod\s+env\s*;",
        "crate-internal Rust environment model module is public",
    ),
    _forbid(
        "rust-public-model-root-reexports",
        "frontend/src-tauri/src/models/mod.rs",
        r"^pub\s+use\b",
        "crate-internal Rust model re-export is public",
    ),
    _forbid(
        "frontend-resume-inspection-protocol-mirror",
        "frontend/src/types/domain/batch.ts",
        r"^export\s+interface\s+ResumeInspectionResult\b",
        "manual frontend resume inspection protocol mirror",
    ),
    _forbid(
        "frontend-resume-status-protocol-mirror",
        "frontend/src/types/domain/batch.ts",
        r"^export\s+interface\s+ResumeStatus\b",
        "manual frontend resume status protocol mirror",
    ),
    _forbid(
        "frontend-resume-mode-protocol-mirror",
        "frontend/src/types/domain/batch.ts",
        r"^export\s+type\s+ResumeMode\b",
        "manual frontend resume mode protocol mirror",
    ),
    _forbid(
        "frontend-video-info-result-alias",
        "frontend/src/types/domain/media.ts",
        r"^export\s+type\s+VideoInfoResult\s*=",
        "redundant frontend video info protocol alias",
    ),
    _forbid(
        "python-error-inference-string-interface",
        "backend/app/errors/_bootstrap.py",
        r"def\s+infer_error_code\s*\([^)]*(?:BaseException\s*\|\s*str|exc_or_message)|isinstance\s*\(\s*exc_or_message|_match_by_message\s*\(\s*exc_or_message",
        "test-only string error inference interface",
    ),
    _forbid(
        "rust-command-manifest-test-interface",
        "frontend/src-tauri/src/commands_manifest.rs",
        r"#\s*\[\s*allow\s*\(\s*dead_code\s*\)\s*\]|\bpub\s+const\s+APP_COMMAND_NAMES\b",
        "test-only public command manifest interface",
    ),
    _forbid(
        "rust-command-manifest-module",
        "frontend/src-tauri/src/lib.rs",
        r"^\s*mod\s+commands_manifest\s*;",
        "test-only command manifest module",
    ),
    RequiredPatternRule(
        "rust-command-manifest-test-include",
        "frontend/src-tauri/src/lib.rs",
        r"#\s*\[\s*cfg\s*\(\s*test\s*\)\s*\]\s*mod\s+tests\s*\{[\s\S]{0,300}include!\s*\(\s*[\"']commands_manifest\.rs[\"']\s*\)\s*;",
        "Rust tests must consume the private command manifest directly",
    ),
    _forbid(
        "protocol-reporter-metrics-view-import",
        "backend/app/protocol/reporter.py",
        r"app\.protocol\.metrics_view|\bMetricsSnapshot\b",
        "obsolete public metrics view interface",
    ),
    RequiredPatternRule(
        "protocol-reporter-private-metrics-contract",
        "backend/app/protocol/reporter.py",
        r"class\s+_MetricsSnapshot\s*\(\s*Protocol\s*\)[\s\S]{0,200}def\s+snapshot\s*\(",
        "reporter private metrics contract is missing",
    ),
    _forbid(
        "frame-filter-write-only-logger",
        "backend/app/processing/frame_filters.py",
        r"from\s+app\.utils\.logger\s+import\s+get_logger|^\s*logger\s*=\s*get_logger\s*\(\s*__name__\s*\)",
        "write-only frame filter logger",
    ),
    _forbid(
        "frame-filter-imperative-dispatch",
        "backend/app/processing/frame_filters.py",
        r"kind\s+not\s+in\s+\{|getattr\s*\(\s*self\s*,\s*f?[\"']_apply_|^\s+def\s+_apply_(?:tensor_)?(?:scale|crop|pad|sharpen|denoise|color|anime_cleanup)\b|^\s*(?:if|elif)\s+kind\s*==",
        "frame-filter orchestration contains concrete handler or imperative dispatch logic",
    ),
    _forbid(
        "rust-untyped-resume-inspection-command",
        "frontend/src-tauri/src/tasks/commands.rs",
        r"check_resume_state[\s\S]{0,300}->\s*Result<\s*Value\b",
        "resume inspection command returns untyped JSON",
    ),
    RequiredPatternRule(
        "rust-typed-resume-inspection-command",
        "frontend/src-tauri/src/tasks/commands.rs",
        r"check_resume_state[\s\S]{0,500}serde_json::from_value::<ResumeInspectionResult>",
        "resume inspection command must validate the backend payload",
    ),
    RequiredPatternRule(
        "generated-resume-inspection-contract",
        "frontend/src/types/generated/ResumeInspectionResult.ts",
        r"type:\s*ResumeInspectionEventType[\s\S]*pipeline_kind:\s*ResumePipelineKind[\s\S]*input_path:\s*string",
        "generated resume inspection TypeScript contract is missing",
    ),
    RequiredPatternRule(
        "resume-inspection-json-schema",
        "frontend/src-tauri/schemas/resume_inspection_result.schema.json",
        r"[\"']pipeline_kind[\"'][\s\S]*[\"']input_path[\"']",
        "resume inspection JSON Schema is missing",
    ),
    RequiredPatternRule(
        "rust-resume-mode-contract",
        "frontend/src-tauri/src/models/task.rs",
        r"enum\s+ResumeMode\s*\{\s*Auto,\s*ForceFresh,\s*ForceResume,?\s*\}[\s\S]*?pub\s+struct\s+TaskRequest[\s\S]*?pub\s+resume_mode:\s*Option<ResumeMode>",
        "Rust TaskRequest resume mode contract is missing",
    ),
    RequiredPatternRule(
        "frontend-resume-mode-protocol-export",
        "frontend/src/types/protocol/index.ts",
        r"export\s+type\s+\{\s*ResumeMode\s*\}\s+from\s+[\"']@/types/generated/ResumeMode[\"']",
        "frontend protocol must export the generated resume mode",
    ),
    RequiredPatternRule(
        "task-request-resume-mode-schema",
        "frontend/src-tauri/schemas/task_request.schema.json",
        r"[\"']resumeMode[\"'][\s\S]*[\"']\$ref[\"']\s*:\s*[\"']#\/\$defs\/ResumeMode[\"'][\s\S]*[\"']force-fresh[\"'][\s\S]*[\"']force-resume[\"']",
        "TaskRequest JSON Schema must constrain resume mode",
    ),
    _forbid(
        "rust-runtime-output-dir-state",
        "frontend/src-tauri/src/runtime/mod.rs",
        r"\bpub\s+output_dir\s*:|app_data_dir\.join\([\"']output[\"']\)",
        "dead runtime output directory state",
    ),
    _forbid(
        "rust-environment-fingerprint-output-dir",
        "frontend/src-tauri/src/persistence/storage.rs",
        r"[\"']outputDir[\"']\s*:\s*paths\.output_dir\b",
        "output path contaminates environment capability fingerprint",
    ),
    _forbid(
        "python-obsolete-environment-fields",
        "backend/app/cli/commands/check.py",
        r"\bbackend_device_support\b|[\"']backendDeviceSupport[\"']|[\"']sequenceMode[\"']",
        "obsolete Python environment payload field",
    ),
    _forbid(
        "runtime-config-snapshots",
        "backend/app/cli/runtime_configs.py",
        r"\b(?:decode_json|encode_json|workflow_json|output_json|legacy_sections|with_workflow_json)\b|^ConfigSection\s*=",
        "duplicate RuntimeConfigs JSON snapshot surface",
    ),
    _forbid(
        "public-config-model-typevar",
        "backend/app/cli/commands/_process_validation.py",
        r"^ConfigModel\s*=",
        "module-internal config model TypeVar is public",
    ),
    _forbid(
        "public-ffmpeg-avoption-parser",
        "backend/app/utils/ffmpeg/capability_probe.py",
        r"^def\s+parse_avoptions\b",
        "module-internal FFmpeg AVOption parser is public",
    ),
    _forbid(
        "public-paddlegan-runner-constants",
        "backend/app/algorithms/paddle/paddlegan_vsr/runner.py",
        r"^(?:TRACE_ENV_VAR|TENSORRT_LOG_PREFIX)\s*=",
        "module-internal PaddleGAN runner constant is public",
    ),
    ForbiddenReferenceRule(
        "duplicate-tensorrt-log-marker",
        roots=("backend/app",),
        patterns=(r"[\"']\[VP_TRT\][\"']",),
        message="duplicate TensorRT subprocess log marker",
        suffixes=(".py",),
        excludes=("backend/app/protocol/process_markers.py",),
    ),
    _forbid(
        "benchmark-test-runner-parameter",
        "backend/app/benchmark/runner.py",
        r"\bprocess_runner\b",
        "benchmark test-only process runner parameter",
    ),
    _forbid(
        "benchmark-command-test-runner",
        "backend/app/cli/commands/benchmark.py",
        r"\bargs\.runner\b|getattr\s*\(\s*args\s*,\s*[\"']runner[\"']",
        "benchmark command test-only runner entry",
    ),
    _forbid(
        "public-settings-model",
        "backend/app/config.py",
        r"^\s*class\s+Settings\b",
        "module-internal Settings model is public",
    ),
    _forbid(
        "public-benchmark-helpers",
        "backend/app/benchmark/runner.py",
        r"^\s*(?:class\s+BenchmarkRun\b|def\s+(?:parse_process_stdout|build_report|generate_synthetic_input|run_process_once)\b)",
        "module-internal benchmark helper is public",
    ),
    _forbid(
        "public-benchmark-reporting-helper",
        "backend/app/benchmark/reporting.py",
        r"^\s*def\s+render_markdown_report\b",
        "module-internal benchmark reporting helper is public",
    ),
    _forbid(
        "public-reporter-formatters",
        "backend/app/protocol/reporter.py",
        r"^\s*def\s+(?:emit_terminal|format_eta|format_progress_bar)\b",
        "module-internal reporter formatter is public",
    ),
    _forbid(
        "public-resume-decision",
        "backend/app/planning/manifest.py",
        r"^\s*class\s+ResumeDecision\b",
        "module-internal resume decision is public",
    ),
    _forbid(
        "public-stage-file-context",
        "backend/app/processing/streaming/stage_file_stage_context.py",
        r"^\s*class\s+StageFileStageContext\b",
        "module-internal stage-file context is public",
    ),
    _forbid(
        "public-paddlegan-weight-helpers",
        "backend/app/algorithms/paddle/paddlegan_vsr/weights.py",
        r"^\s*(?:class\s+PaddleGanVsrSpec\b|def\s+(?:resolve_weight_path|ensure_weight_file)\b)",
        "module-internal PaddleGAN weight helper is public",
    ),
    _forbid(
        "public-ffmpeg-command-builders",
        "backend/app/utils/ffmpeg/io.py",
        r"^\s*def\s+(?:build_rawvideo_decode_command|build_rawvideo_encode_command)\b",
        "module-internal FFmpeg command builder is public",
    ),
    _forbid(
        "public-ffmpeg-encode-builder",
        "backend/app/utils/ffmpeg/encode.py",
        r"^\s*def\s+build_encode_video_args\b",
        "module-internal FFmpeg encode builder is public",
    ),
    _forbid(
        "ipc-error-export",
        "frontend/src/lib/ipc/client.ts",
        r"^\s*export(?:\s+class\s+InvokeError\b|\s*\{[^}\n]*\bInvokeError\b)",
        "test-only IPC error export",
    ),
    _forbid(
        "compile-contract-export",
        "frontend/src/types/protocol/_contract_check.ts",
        r"^\s*export\s+const\s+_[A-Z0-9_]+_CONTRACT\b",
        "compile-only contract export",
    ),
    _forbid(
        "ipc-contract-internal-exports",
        "frontend/src/lib/ipc/contract.ts",
        r"export\s+(?:interface\s+(?:IpcCommandArgs|IpcCommandResult)|type\s+TaskControlKind)|(?:export\s+)?const\s+IPC_COMMAND_NAMES\b",
        "internal IPC contract surface exported",
    ),
    _forbid(
        "paddlegan-disabled-registry",
        "backend/app/algorithms/paddle/paddlegan_vsr/weights.py",
        r"\bDISABLED_PADDLEGAN_VSR_MODELS\b|^\s*def\s+(?:resolve_auxiliary_weight_path|ensure_auxiliary_weight_file)\b",
        "dead PaddleGAN weight surface",
    ),
    _forbid(
        "workflow-validation-dead-surface",
        "backend/app/planning/workflow_validation.py",
        r"\bDISABLED_PADDLEGAN_VSR_MODELS\b|^\s*def\s+(?:get_onnx_model_name|validate_onnx_models_for_workflow)\b",
        "dead workflow validation surface",
    ),
    _forbid(
        "processing-bootstrap",
        "backend/app/processing/__init__.py",
        r"\bregister_default_algorithms\b",
        "global processing bootstrap",
    ),
    _forbid(
        "cli-package-facade",
        "backend/app/cli/__init__.py",
        r"from\s+app\.cli\.(?:commands|parser)\b|\bPROCESS_(?:LABEL|ORDER)_MAP\b",
        "unused CLI package facade",
    ),
    _forbid(
        "planning-package-facade",
        "backend/app/planning/__init__.py",
        r"\b(?:AlgorithmType|PROCESS_LABEL_MAP|ResumeDecision|RunIdentity|SegmentRecord|estimate_encoded_output_frames|ResumeKind|get_onnx_model_name|processing_needs_interpolation|validate_onnx_models_for_workflow)\b",
        "unused planning package facade",
    ),
    _forbid(
        "public-run-identity-result",
        "backend/app/planning/run_identity.py",
        r"^class\s+RunIdentity\b|__all__\s*=\s*\[[^\]]*[\"']RunIdentity[\"']",
        "module-internal run identity result is public",
    ),
    _forbid(
        "ffmpeg-dead-delegates",
        "backend/app/utils/ffmpeg/__init__.py",
        r"^\s*def\s+(?:list_codec_names|list_hwaccels|describe_codec|parse_codec_profile|parse_avoptions|probe_rate_control_modes|probe_decoder_hardware_devices|probe_decoder_hardware_device_options|build_decode_input_args|build_encode_output_args|build_rawvideo_decode_command|build_rawvideo_encode_command|convert_format|build_encode_video_args)\b|__all__\s*=\s*\[[^\]]*\b(?:RawVideoReader|RawVideoWriter|build_rawvideo_|open_rawvideo_)",
        "unused FFmpeg facade",
    ),
    _forbid(
        "python-super-resolution-auto-download-field",
        "backend/app/models/__init__.py",
        r"\bauto_download_weights\b",
        "removed super-resolution auto-download field",
    ),
    _forbid(
        "rust-super-resolution-auto-download-field",
        "frontend/src-tauri/src/models/config.rs",
        r"\bdefault_auto_download_weights\b|pub\s+auto_download_weights\s*:",
        "removed Rust super-resolution auto-download field",
    ),
    _forbid(
        "public-segment-record",
        "backend/app/planning/manifest.py",
        r"^class\s+SegmentRecord\b",
        "internal segment record is public",
    ),
    _forbid(
        "public-reporter-progress-constants",
        "backend/app/protocol/reporter.py",
        r"^(?:TERMINAL_PROGRESS_PREFIX|TERMINAL_PROGRESS_BAR_WIDTH)\s*=",
        "internal reporter progress constant is public",
    ),
    _forbid(
        "public-error-code-cache",
        "backend/app/errors/_codes.py",
        r"^ALL_CODES\s*=",
        "internal error-code cache is public",
    ),
    _forbid(
        "public-onnx-internals",
        "backend/app/utils/onnx_models.py",
        r"^(?:OnnxModelKind|ONNX_MODEL_SUBDIRS)\s*=|^def\s+(?:is_safe_onnx_basename|is_safe_algorithm_name|select_onnx_providers)\b",
        "internal ONNX helper is public",
    ),
    _forbid(
        "public-system-probe-constants",
        "backend/app/utils/system_probe.py",
        r"^(?:GPU_VENDOR_KEYWORDS|VIRTUAL_GPU_KEYWORDS)\s*=",
        "internal system probe constant is public",
    ),
    _forbid(
        "public-file-extension-constant",
        "backend/app/utils/file_utils.py",
        r"^SUPPORTED_EXTENSIONS\s*=",
        "internal file extension constant is public",
    ),
    _forbid(
        "public-paddlegan-weight-root",
        "backend/app/algorithms/paddle/paddlegan_vsr/weights.py",
        r"^def\s+fixed_weight_root\b",
        "internal PaddleGAN weight root is public",
    ),
    _forbid(
        "ffmpeg-dead-converter",
        "backend/app/utils/ffmpeg/encode.py",
        r"^\s*def\s+convert_format\b",
        "dead FFmpeg format converter",
    ),
    _forbid(
        "algorithm-base-test-api",
        "backend/app/algorithms/base.py",
        r"^\s*def\s+(?:process_frame_batch|validate|get_description)\b",
        "test-only algorithm API",
    ),
    *(
        _forbid(
            f"algorithm-implementation-test-api-{index}",
            path,
            r"^\s*def\s+(?:process_frame_batch|validate|get_description)\b",
            "test-only concrete algorithm API",
        )
        for index, path in enumerate(
            (
                "backend/app/processing/frame_filters.py",
                "backend/app/processing/interpolation.py",
                "backend/app/processing/super_resolution.py",
            )
        )
    ),
    _forbid(
        "legacy-anime-workflow-model",
        "backend/app/models/__init__.py",
        r"\bclass\s+AnimeConfig\b|^\s*anime\s*:\s*AnimeConfig\b|[\"']anime_optimization[\"']",
        "legacy anime workflow model",
    ),
    _forbid(
        "legacy-anime-cli",
        "backend/app/cli/parser.py",
        r"[\"']anime_optimization[\"']|--anime-",
        "legacy anime CLI surface",
    ),
    _forbid(
        "legacy-anime-enhance-view",
        "frontend/src/views/EnhanceModuleView.vue",
        r"\banime(?:Enabled|Profile|Denoise|EdgeBoost|Profiles)\b|动漫优化",
        "legacy standalone anime enhance controls",
    ),
    _forbid(
        "legacy-anime-enhance-bindings",
        "frontend/src/composables/forms/enhance-form-bindings.ts",
        r"\banime(?:Enabled|Profile|Denoise|EdgeBoost|Profiles)\b",
        "legacy standalone anime form binding",
    ),
    _forbid(
        "legacy-environment-result-fields",
        "frontend/src-tauri/src/models/env.rs",
        r"pub\s+struct\s+(?:TensorBackends|OnnxRuntimeInfo|RifeModel|RuntimeInfo|ResourceInfo)\b|pub\s+struct\s+EnvironmentCheckResult\s*\{[\s\S]*?pub\s+(?:r#type|tensor_backends|onnx_runtime|rife_model|resources|runtime|anime_profiles)\s*:",
        "obsolete environment result field",
    ),
    _forbid(
        "legacy-environment-diagnostics",
        "backend/app/cli/commands/check.py",
        r"[\"'](?:onnxRuntime|rifeModel|animeProfiles|weightPath|weightAvailable|pixelFormats|ffmpegPath|ffprobePath)[\"']|\bget_version\s*\(",
        "obsolete environment diagnostic payload",
    ),
    _forbid(
        "legacy-video-info-fields",
        "frontend/src-tauri/src/models/task.rs",
        r"pub\s+struct\s+VideoInfo\s*\{[\s\S]*?pub\s+(?:r#type|frames|duration|has_audio)\s*:",
        "obsolete inspect-video result field",
    ),
    _forbid(
        "legacy-task-store-reset",
        "frontend/src/stores/task.ts",
        r"\bresetBatch\b",
        "dead task store reset interface",
    ),
    _forbid(
        "legacy-encoded-frame-index",
        "backend/app/processing/streaming/queues.py",
        r"\boutput_index\b",
        "dead encoded-frame output index",
    ),
    _forbid(
        "legacy-preflight-resolved-steps-field",
        "backend/app/processing/streaming/pipeline_preflight.py",
        r"\bresolved_steps\b",
        "redundant preflight resolved-steps alias",
    ),
    _forbid(
        "metrics-dead-timing-api",
        "backend/app/processing/streaming/metrics.py",
        r"^\s*def\s+(?:timed|record_stage_duration)\b|\bstage_durations\b",
        "unused pipeline metrics timing API",
    ),
    _forbid(
        "stage-worker-helper-definitions",
        "backend/app/processing/streaming/stage_worker.py",
        r"^\s*(?:class\s+RawVideoFrameError\b|def\s+(?:read_rgb_frame|write_rgb_frame|emit_stage_event|_create_backend|_create_algorithm|_run_sequence_stage|_run_interpolation_stage|_run_single_frame_stage)\b)",
        "stage worker helper implementation",
    ),
    _forbid(
        "worker-process-helper-definitions",
        "backend/app/processing/streaming/worker_processes.py",
        r"^\s*def\s+(?:parse_stage_event_line|read_worker_stderr|write_decoded_frames_to_worker|drain_final_worker_output|close_pipe)\b",
        "worker process event or IO implementation",
    ),
    _forbid(
        "pipeline-runtime-coupling",
        "backend/app/processing/streaming/pipeline.py",
        r"from\s+app\.processing\.streaming\.(?:pipeline_raw|stage_file_pipeline|worker_pipeline)\s+import|\b(?:queue\.Queue|threading\.Thread|threading\.Event|run_stage_worker_pipeline)\b",
        "streaming entrypoint runtime coupling",
    ),
    _forbid(
        "raw-private-worker-coupling",
        "backend/app/processing/streaming/pipeline_raw.py",
        r"from\s+app\.processing\.streaming\.(?:encoder|encoder_worker)\s+import|\bstage_worker_runner\b|\bsignature\b",
        "raw pipeline private runtime coupling",
    ),
    _forbid(
        "worker-pipeline-process-io",
        "backend/app/processing/streaming/worker_pipeline.py",
        r"from\s+app\.processing\.streaming\.(?:worker_processes|worker_process_events|worker_process_io)\s+import",
        "worker pipeline process IO coupling",
    ),
    _forbid(
        "frontend-decode-form-business-rules",
        "frontend/src/composables/forms/useDecodeForm.ts",
        r"@/services/preset/",
        "decode composable business rule",
    ),
    _forbid(
        "frontend-encode-form-business-rules",
        "frontend/src/composables/forms/useEncodeForm.ts",
        r"@/services/preset/",
        "encode composable business rule",
    ),
    _forbid(
        "frontend-enhance-form-business-rules",
        "frontend/src/composables/forms/useEnhanceForm.ts",
        r"@/services/preset/|createAlgorithmLens|buildEnhanceViewModel|createDraftEditor",
        "enhance composable business rule",
    ),
    _forbid(
        "frontend-enhance-form-direct-rules",
        "frontend/src/composables/forms/enhance-form-bindings.ts",
        r"@/services/preset/(?:enhance-workflow|enhance-view-model)|createDraftEditor|createEnhanceFieldBindings",
        "enhance form direct business rule",
    ),
    _forbid(
        "frontend-io-view-rules-decode",
        "frontend/src/views/DecodeModuleView.vue",
        r"@/services/preset/(?:io-options|io-form-rules|profile-selection)|\bas\s+RateControlMode\b|\bNumber\s*\(",
        "decode view option conversion rule",
    ),
    _forbid(
        "frontend-io-view-rules-encode",
        "frontend/src/views/EncodeModuleView.vue",
        r"@/services/preset/(?:io-options|io-form-rules|profile-selection)|\bas\s+RateControlMode\b|\bNumber\s*\(",
        "encode view option conversion rule",
    ),
    _forbid(
        "frontend-enhance-view-rules",
        "frontend/src/views/EnhanceModuleView.vue",
        r"@/services/preset/enhance-options|useGpuCapabilities|\bas\s+(?:TensorBackend|InferenceEngine|ProcessOrder)\b|\bNumber\s*\(",
        "enhance view option conversion rule",
    ),
    _forbid(
        "frontend-default-workflow-hydration",
        "frontend/src/services/preset/defaults.ts",
        r"enhance-rules|pickDefault|tensorEngines|gpu\?\.adapters|\bvendor\b",
        "workflow environment hydration outside owner",
    ),
    _forbid(
        "ndjson-emitter-singleton",
        "backend/app/protocol/__init__.py",
        r"\bclass\s+NdjsonEmitter\b|\b_instance\b|^\s*def\s+__new__\b",
        "public or singleton NDJSON emitter",
    ),
    _forbid(
        "base-select-local-option-type",
        "frontend/src/components/forms/BaseSelect.vue",
        r"^\s*(?:export\s+)?interface\s+SelectOption\b",
        "local SelectOption type",
    ),
    *(
        _forbid(
            f"preset-local-option-type-{index}",
            path,
            r"^\s*(?:export\s+)?interface\s+SelectOption\b",
            "preset-local SelectOption type",
        )
        for index, path in enumerate(
            (
                "frontend/src/services/preset/enhance-options.ts",
                "frontend/src/services/preset/io-options.ts",
                "frontend/src/services/preset/rate-control.ts",
            )
        )
    ),
    _forbid(
        "batch-lifecycle-type-reexport",
        "frontend/src/services/task/batch/lifecycle/index.ts",
        r"\bexport\s+type\s*\{[^}]*\bBatchLifecycle(?:Deps)?\b",
        "batch lifecycle facade type re-export",
    ),
    _forbid(
        "batch-lifecycle-interface-mirror",
        "frontend/src/services/task/batch/lifecycle/types.ts",
        r"\binterface\s+BatchLifecycle\b",
        "handwritten BatchLifecycle return interface mirror",
    ),
    _forbid(
        "batch-runner-duplicate-deps",
        "frontend/src/services/task/batch-runner.ts",
        r"^\s*interface\s+BatchRunnerDeps\b",
        "duplicate BatchRunnerDeps",
    ),
    _forbid(
        "batch-queue-unused-helpers",
        "frontend/src/services/task/batch/lifecycle/queue.ts",
        r"\b_helpers\s*:\s*CommonHelpers\b",
        "unused batch queue helpers dependency",
    ),
    _forbid(
        "media-import-dead-draft-apply",
        "frontend/src/composables/app/useMediaImport.ts",
        r"\bapplyDraftToSelectedItems\b",
        "unwired draft-to-selection media import hook",
    ),
    _forbid(
        "oneshot-unused-app-context",
        "frontend/src-tauri/src/tasks/oneshot.rs",
        r"\b(?:AppHandle|Runtime)\b|\blet\s+_\s*=\s*app\b",
        "unused one-shot app context",
    ),
    _forbid(
        "protocol-error-code-reexport",
        "frontend/src-tauri/src/protocol.rs",
        r"\bTaskErrorCode\b",
        "TaskErrorCode compatibility re-export",
    ),
    ForbiddenReferenceRule(
        "typed-processing-step-contract",
        roots=("backend/app",),
        patterns=(
            r"\bProcessingStepInput\b",
            r"\bnormalize_processing_step(?:s)?\b",
            r"\bprocessing_steps_to_jsonable\b",
        ),
        message="legacy processing-step mapping interface",
        suffixes=(".py",),
    ),
    _forbid(
        "processing-step-required-fields",
        "backend/app/planning/processing_steps.py",
        r"algorithm_kwargs\s*:[^\n=]+\s*=|stage_name\s*:[^\n=]+\s*=",
        "optional processing-step field",
    ),
    _forbid(
        "process-error-dead-exit-code",
        "backend/app/errors/__init__.py",
        r"\bexit_code\b",
        "write-only process error exit code",
    ),
    ForbiddenReferenceRule(
        "process-error-dead-exit-code-call",
        roots=("backend/app",),
        patterns=(r"\braise_error\s*\([\s\S]{0,500}?\bexit_code\s*=",),
        message="write-only process error exit code argument",
        suffixes=(".py",),
    ),
    _forbid(
        "stage-worker-config-implementation",
        "backend/app/processing/streaming/stage_worker.py",
        r"^\s*class\s+StageWorkerConfig\b|^\s+def\s+(?:from_json_file|to_jsonable)\b|\bnormalize_processing_step\b|\bjson\.load\b",
        "stage worker config implementation",
    ),
    _forbid(
        "pipeline-owned-lifecycle",
        "backend/app/processing/streaming/pipeline.py",
        r"\bResumeConflictError\b|\.prepare\s*\(|\bdecision\.kind\b|\.cleanup\s*\(|\bget_frame_count\s*\(|\bresume_status\b",
        "streaming lifecycle implementation",
    ),
    _forbid(
        "pipeline-owned-preflight",
        "backend/app/processing/streaming/pipeline.py",
        r"\b(?:resolve_video_info|build_stage_plan|build_run_identity|should_use_stage_file_pipeline|stage_file_resume_source_frames|resolved_output_dimensions)\b|from\s+app\.processing\.streaming\.pipeline_rules\s+import",
        "streaming preflight implementation",
    ),
    ForbiddenReferenceRule(
        "obsolete-run-identity-builders",
        roots=(
            "backend/app",
            "backend/tests",
            "docs/04-backend-architecture.md",
            "docs/09-resume-checkpointing.md",
        ),
        patterns=(r"\bbuild_signature\b", r"\bbuild_config_snapshot\b"),
        message="split run-identity builder",
        suffixes=(".py", ".md"),
    ),
    _forbid(
        "stage-plan-run-identity-coupling",
        "backend/app/planning/stage_plan.py",
        r"\b(?:hashlib|signature|config_snapshot|decode_config|encode_config|workflow_config|output_config)\b",
        "run identity implementation in stage-plan rules",
    ),
    _forbid(
        "pipeline-rules-run-identity-coupling",
        "backend/app/processing/streaming/pipeline_rules.py",
        r"\b(?:config_snapshot|input_path|output_path|decode_config|encode_config|workflow_config|output_config|processing_steps)\b",
        "run identity implementation in pipeline rules",
    ),
    _forbid(
        "run-identity-streaming-dependency",
        "backend/app/planning/run_identity.py",
        r"\bapp\.processing\b",
        "planning run identity dependency on streaming",
    ),
    RequiredPatternRule(
        "preflight-run-identity",
        "backend/app/processing/streaming/pipeline_preflight.py",
        r"\bidentity\s*=\s*build_run_identity\s*\(",
        "streaming preflight must build one shared run identity",
    ),
    _forbid(
        "backend-architecture-stale-stage-plan-fields",
        "docs/04-backend-architecture.md",
        r"\b(?:total_output_frames|total_pairs)\b|list\[dict\]",
        "stale StagePlan field documentation",
    ),
    _forbid(
        "pipeline-dispatch-worker-coupling",
        "backend/app/processing/streaming/pipeline_dispatch.py",
        r"from\s+app\.processing\.streaming\.worker_pipeline\s+import|\bstage_worker_runner\b|\brun_stage_worker_pipeline\b",
        "pipeline dispatch worker coupling",
    ),
    _forbid(
        "encoder-finalization-signature",
        "backend/app/processing/streaming/encoder_finalization.py",
        r"\bsignature\b",
        "encoder finalization signature forwarding",
    ),
    _forbid(
        "pipeline-lifecycle-finalization-signature",
        "backend/app/processing/streaming/pipeline_lifecycle.py",
        r"def\s+finalize_streaming_output\s*\([\s\S]*?\bsignature\s*:|finalize_segmented_output\s*\([\s\S]*?\bsignature\s*=",
        "pipeline lifecycle finalization signature forwarding",
    ),
    _forbid(
        "stage-file-finalization-signature",
        "backend/app/processing/streaming/stage_file_pipeline.py",
        r"finalize_segmented_output\s*\([\s\S]*?\bsignature\s*=",
        "stage-file finalization signature forwarding",
    ),
    _forbid(
        "pipeline-output-dimensions-backend",
        "backend/app/processing/streaming/pipeline_rules.py",
        r"def\s+resolved_output_dimensions\s*\([\s\S]*?\btensor_backend_name\b|\bdel\s+tensor_backend_name\b",
        "output dimensions backend parameter",
    ),
    _forbid(
        "worker-pipeline-plan-implementation",
        "backend/app/processing/streaming/worker_pipeline.py",
        r"^\s*(?:class\s+(?:StageWorkerPlan|StageChunkPlan)\b|def\s+(?:build_stage_worker_plans|build_stage_chunk_plans|boundary_schedule_for_stage_plan)\b)|from\s+app\.processing\.streaming\.worker_plans\s+import\s*\([\s\S]*\b(?:StageChunkPlan|StageWorkerPlan|boundary_schedule_for_stage_plan|build_stage_chunk_plans)\b|__all__\s*=\s*\[[\s\S]*[\"'](?:StageChunkPlan|StageWorkerPlan|boundary_schedule_for_stage_plan|build_stage_chunk_plans)[\"']",
        "worker plan implementation",
    ),
    _forbid(
        "stage-file-pipeline-chunk-implementation",
        "backend/app/processing/streaming/stage_file_pipeline.py",
        r"^\s*def\s+(?:_?run_single_stage_file_chunks|_?run_stage_chunk_to_file|_?stage_signature|_?safe_stage_name)\b|from\s+app\.processing\.streaming\.stage_file_rules\s+import|\bSegmentManifest\s*\(|\bstage_signature\s*\(|\bsafe_stage_name\s*\(",
        "stage-file chunk implementation",
    ),
    _forbid(
        "encoder-worker-segment-implementation",
        "backend/app/processing/streaming/encoder_worker.py",
        r"^\s*from\s+pathlib\s+import\s+Path\b|^\s*import\s+os\b|\bopen_rawvideo_encoder\b|\bwriter\.(?:write_frame|close)\s*\(|\bfinalize_chunk\s*\(|\bchunk_tmp_path\s*\(|\b(?:_?make_segment_progress_callback|_?resolve_segment_output_frame_count)\b|\bunlink\s*\(|\b(?:current_segment_input_frames|segment_index|tmp_path)\b",
        "encoder worker segment writer implementation",
    ),
    _forbid(
        "stage-file-chunks-runtime",
        "backend/app/processing/streaming/stage_file_chunks.py",
        r"^\s*def\s+run_stage_chunk_to_file\b|^\s*import\s+(?:queue|tempfile|threading)\b|\b(?:StageWorkerConfig|read_rgb_frame|spawn_stage_workers|write_decoded_frames_to_worker)\b|^from\s+app\.processing\.streaming\.stage_file_chunk_runtime\s+import\s+run_stage_chunk_to_file\s*$|\b_run_stage_chunk_to_file\s*\(|__all__\s*=\s*\[[\s\S]*[\"']run_stage_chunk_to_file[\"']",
        "stage-file chunk runtime implementation",
    ),
    _forbid(
        "stage-file-chunk-input-fps",
        "backend/app/processing/streaming/stage_file_chunks.py",
        r"def\s+run_single_stage_file_chunks\s*\([\s\S]*?\binput_fps\b|\bdel\s+input_fps\b",
        "stage-file chunk input_fps parameter",
    ),
    _forbid(
        "stage-file-input-fps-forwarding",
        "backend/app/processing/streaming/stage_file_pipeline.py",
        r"run_single_stage_file_chunks\s*\([\s\S]*?\binput_fps\s*=",
        "stage-file chunk input_fps forwarding",
    ),
    _forbid(
        "manifest-sidecar-reset-duplicate",
        "backend/app/planning/manifest.py",
        r"^\s*def\s+_reset_sidecar\b|\bself\._reset_sidecar\s*\(",
        "duplicate manifest sidecar reset lifecycle",
    ),
    _forbid(
        "runtime-config-positional-interface",
        "backend/app/cli/runtime_configs.py",
        r"^\s*def\s+legacy_tuple\b",
        "positional runtime config interface",
    ),
    _forbid(
        "manifest-test-only-public-helpers",
        "backend/app/planning/manifest.py",
        r"^[ \t]{4}def\s+(?:chunk_final_path|cleanup_partial|cleanup_stale_chunks)\b",
        "test-only public manifest helper",
    ),
    _forbid(
        "stage-worker-config-mapping-interface",
        "backend/app/processing/streaming/stage_worker_config.py",
        r"^[ \t]{4}def\s+from_mapping\b",
        "test-only stage-worker mapping interface",
    ),
    _forbid(
        "preset-sync-test-only-return",
        "frontend/src/composables/app/usePresetSync.ts",
        r"^[ \t]{4}(?:persistDraft|scheduleSave),\s*$|loadPersistedPreset\(\):\s*Promise<boolean>",
        "test-only preset sync return field",
    ),
    _forbid(
        "media-import-test-only-result",
        "frontend/src/composables/app/useMediaImport.ts",
        r"pickAndImport\(\):\s*Promise<\{",
        "test-only media import result",
    ),
    _forbid(
        "output-picker-test-only-result",
        "frontend/src/composables/app/useOutputPicker.ts",
        r"pickOutputDirectory\(\):\s*Promise<\{",
        "test-only output picker result",
    ),
    _forbid(
        "decode-profile-test-only-return",
        "frontend/src/composables/forms/decode-profile-bindings.ts",
        r"^[ \t]{4}visibleDecoderProfiles,\s*$",
        "test-only decode profile return field",
    ),
    _forbid(
        "encode-profile-test-only-return",
        "frontend/src/composables/forms/encode-profile-bindings.ts",
        r"^[ \t]{4}visibleEncoderProfiles,\s*$",
        "test-only encode profile return field",
    ),
    _forbid(
        "encode-rate-control-test-only-return",
        "frontend/src/composables/forms/encode-rate-control-bindings.ts",
        r"^[ \t]{4}setRateControlMode,\s*$",
        "test-only rate-control return field",
    ),
    _forbid(
        "enhance-onnx-alias-return",
        "frontend/src/composables/forms/enhance-algorithm-bindings.ts",
        r"^[ \t]{4}isOnnxBackend(?:\s*:|,)\s*",
        "ambiguous interpolation ONNX alias",
    ),
    _forbid(
        "home-dashboard-internal-profile-return",
        "frontend/src/composables/selectors/useHomeDashboard.ts",
        r"^[ \t]{4}visibleEncoderProfiles,\s*$",
        "internal home dashboard profile return field",
    ),
    _forbid(
        "stage-file-chunk-encoding-leak",
        "backend/app/processing/streaming/stage_file_chunk_runtime.py",
        r"\bread_rgb_frame\b|\bresolve_segment_output_frame_count\b|\bopen_rawvideo_encoder\b|\bwrite_frame\s*\(|\bwritten_frames\b|Stage chunk output frame count mismatch|\blambda\s+\*_[A-Za-z0-9_]*\s*,\s*\*\*_[A-Za-z0-9_]*\s*:\s*None\b",
        "stage-file chunk encoding implementation",
    ),
    _forbid(
        "obsolete-decode-queue-symbols",
        "backend/app/processing/streaming/queues.py",
        r"\bclass\s+DecodedFrame\b|\bDecodedFrame\b|\b_DECODE_END\b",
        "obsolete decode queue symbol",
    ),
    _forbid(
        "encoder-worker-decode-queue",
        "backend/app/processing/streaming/encoder_worker.py",
        r"\bdecode_queue\b",
        "obsolete encoder decode queue",
    ),
    _forbid(
        "raw-encoder-decode-queue",
        "backend/app/processing/streaming/pipeline_raw_encoder.py",
        r"\bdecode_queue\b",
        "obsolete raw encoder decode queue",
    ),
    *(
        _forbid(
            f"form-binding-param-export-{index}",
            path,
            r"^\s*export\s+(?:interface|type)\s+\w+BindingParams\b",
            "form binding parameter type export",
        )
        for index, path in enumerate(
            (
                "frontend/src/composables/forms/decode-profile-bindings.ts",
                "frontend/src/composables/forms/decode-hardware-bindings.ts",
                "frontend/src/composables/forms/encode-form-bindings.ts",
                "frontend/src/composables/forms/encode-profile-bindings.ts",
                "frontend/src/composables/forms/encode-rate-control-bindings.ts",
                "frontend/src/composables/forms/encode-output-setters.ts",
                "frontend/src/composables/forms/enhance-form-bindings.ts",
                "frontend/src/composables/forms/enhance-algorithm-bindings.ts",
                "frontend/src/composables/forms/enhance-view-bindings.ts",
                "frontend/src/composables/forms/enhance-effect-bindings.ts",
                "frontend/src/composables/forms/enhance-scalar-field-bindings.ts",
            )
        )
    ),
    ForbiddenReferenceRule(
        "filter-step-number-event-glue",
        roots=("frontend/src/components/filter-steps",),
        patterns=(
            r"Number\(\(\$event\.target\s+as\s+HTMLInputElement\)\.value\)",
            r"defineProps<\{[\s\S]*?modelValue:\s*FilterStep",
        ),
        message="duplicated filter-step model or number event glue",
        suffixes=(".vue",),
        excludes=("frontend/src/components/filter-steps/FilterNumberField.vue",),
    ),
    _forbid(
        "batch-runner-interface-mirror",
        "frontend/src/services/task/batch-runner.ts",
        r"\bexport\s+interface\s+BatchRunner\b",
        "handwritten BatchRunner interface mirror",
    ),
    _forbid(
        "batch-event-interface-mirror",
        "frontend/src/services/task/batch/events.ts",
        r"\binterface\s+EventHandlers\b",
        "handwritten batch event interface mirror",
    ),
    ForbiddenReferenceRule(
        "batch-lifecycle-return-interface-mirrors",
        roots=("frontend/src/services/task/batch/lifecycle",),
        patterns=(r"\binterface\s+(?:CommonHelpers|QueueOps|ControlOps|FinalizeOps)\b",),
        message="handwritten lifecycle return interface mirror",
        suffixes=(".ts",),
    ),
    _forbid(
        "preset-sync-duplicate-error-normalization",
        "frontend/src/composables/app/usePresetSync.ts",
        r"\breportPresetIssue\b",
        "duplicated preset persistence error normalization",
    ),
    _forbid(
        "workbench-editor-duplicate-workflow-patcher",
        "frontend/src/composables/selectors/useWorkbenchEditor.ts",
        r"const\s+patchWorkflowAndPreset\s*=\s*\([^)]*\)\s*(?::[^=]+)?=>",
        "duplicate workflow and preset item traversal",
    ),
    _forbid(
        "process-validation-cli-guards",
        "backend/app/cli/commands/_process_validation.py",
        r"\b(?:ensure_input_and_ffmpeg|FFmpegWrapper|validate_input_path)\b",
        "CLI guard implementation in config validation",
    ),
    _forbid(
        "info-direct-ffmpeg-availability-check",
        "backend/app/cli/commands/info.py",
        r"\bFFmpegWrapper\b|\.is_available\s*\(",
        "direct FFmpeg availability check outside CLI guard",
    ),
    _forbid(
        "duplicate-decoder-hardware-verifiers",
        "backend/app/utils/ffmpeg/capability_probe.py",
        r"\b_verify_decoder_hardware_device(?:_option)?\b",
        "duplicated decoder hardware verification helper",
    ),
    _forbid(
        "recursive-decoder-probe-workspace",
        "backend/app/utils/ffmpeg/capability_probe.py",
        r"return\s+probe_decoder_hardware_(?:devices|device_options)\s*\(",
        "recursive decoder probe workspace lifecycle",
    ),
    _forbid(
        "direct-cli-ndjson-error-emission",
        "backend/app/__main__.py",
        r"\bndjson\.error\s*\(",
        "typed CLI error emitted outside shared helper",
    ),
    _forbid(
        "duplicate-dll-root-appends",
        "backend/app/utils/dll_paths.py",
        r"roots\.append\s*\(\s*bin_dir\s*\)",
        "duplicated native DLL directory append logic",
    ),
    *(
        _forbid(
            f"worker-runtime-lifecycle-{index}",
            path,
            r"\b(?:spawn_stage_workers|read_worker_stderr|close_pipe|wait_for_workers|write_decoded_frames_to_worker)\b|threading\.Thread\s*\(|TemporaryDirectory\s*\(",
            "worker process lifecycle outside shared boundary",
        )
        for index, path in enumerate(
            (
                "backend/app/processing/streaming/worker_chain_runtime.py",
                "backend/app/processing/streaming/stage_file_chunk_runtime.py",
            )
        )
    ),
    *(
        _forbid(
            f"video-dimension-stream-loop-{index}",
            path,
            r"for\s+stream\s+in\s+info\.get\([\"']streams[\"']",
            "duplicated primary video dimension traversal",
        )
        for index, path in enumerate(
            (
                "backend/app/planning/stage_plan.py",
                "backend/app/cli/commands/info.py",
            )
        )
    ),
    _forbid(
        "benchmark-direction-comparator-duplicates",
        "backend/app/benchmark/comparison.py",
        r"def\s+_compare_(?:lower|higher)_is_worse\b",
        "duplicated directional benchmark comparator",
    ),
    _forbid(
        "paddlegan-inline-chunk-trace",
        "backend/app/algorithms/paddle/paddlegan_vsr/runner.py",
        r"(?s)^    def _process_(?:recurrent|window)_model\b(?:(?!^    def ).)*trace_chunks\.append",
        "duplicated PaddleGAN chunk trace implementation",
    ),
)


REQUIRED_PATTERN_RULES = (
    RequiredPatternRule(
        "inferred-batch-lifecycle-type",
        "frontend/src/services/task/batch/lifecycle/index.ts",
        r"export\s+type\s+BatchLifecycle\s*=\s*ReturnType<typeof\s+createBatchLifecycle>",
        "BatchLifecycle must be inferred from the facade return value",
    ),
    RequiredPatternRule(
        "shared-cli-guards",
        "backend/app/cli/commands/_guards.py",
        r"def\s+ensure_ffmpeg_available\b[\s\S]*def\s+ensure_input_and_ffmpeg\b",
        "shared CLI guard boundary is missing",
    ),
    RequiredPatternRule(
        "manifest-resume-decision-helpers",
        "backend/app/planning/manifest.py",
        r"def\s+_resume_decision\b[\s\S]*def\s+_prepare_changed_signature\b",
        "shared manifest resume decision helpers are missing",
    ),
    RequiredPatternRule(
        "shared-decoder-hardware-verifier",
        "backend/app/utils/ffmpeg/capability_probe.py",
        r"def\s+_verify_decoder_hardware\b[\s\S]*device_value:\s*str\s*\|\s*None",
        "shared decoder hardware verifier is missing",
    ),
    RequiredPatternRule(
        "shared-decoder-probe-workspace",
        "backend/app/utils/ffmpeg/capability_probe.py",
        r"@contextmanager[\s\S]*def\s+_decoder_probe_workspace\b[\s\S]*TemporaryDirectory\s*\(",
        "shared decoder probe workspace is missing",
    ),
    RequiredPatternRule(
        "shared-dll-directory-dedup",
        "backend/app/utils/dll_paths.py",
        r"def\s+_append_unique_directory\b",
        "shared native DLL directory dedup helper is missing",
    ),
    RequiredPatternRule(
        "declarative-simple-filter-editor",
        "frontend/src/components/FilterChainEditor.vue",
        r"<FilterFields\b[\s\S]*getFilterCatalogEntry\(step\.kind\)\.editor",
        "simple filters must use the declarative catalog editor",
    ),
    RequiredPatternRule(
        "simple-filter-catalog-schema",
        "frontend/src/services/filters/filter-catalog.ts",
        r"kind:\s*[\"']crop[\"'][\s\S]*editor:\s*\{[\s\S]*kind:\s*[\"']pad[\"'][\s\S]*kind:\s*[\"']sharpen[\"'][\s\S]*kind:\s*[\"']denoise[\"'][\s\S]*kind:\s*[\"']color[\"']",
        "simple filter field schemas are missing from the catalog",
    ),
    RequiredPatternRule(
        "shared-filter-number-field",
        "frontend/src/components/filter-steps/FilterNumberField.vue",
        r"\bfunction\s+handleInput\b[\s\S]*emit\([\"']update:modelValue[\"']",
        "shared filter number field is missing",
    ),
    RequiredPatternRule(
        "inferred-batch-runner-type",
        "frontend/src/services/task/batch-runner.ts",
        r"export\s+type\s+BatchRunner\s*=\s*ReturnType<typeof\s+createBatchRunner>",
        "inferred BatchRunner type is missing",
    ),
    RequiredPatternRule(
        "shared-stage-worker-session",
        "backend/app/processing/streaming/worker_processes.py",
        r"def\s+stage_worker_session\b[\s\S]*_spawn_stage_workers\s*\([\s\S]*read_worker_stderr[\s\S]*_wait_for_workers\s*\(",
        "shared stage-worker session lifecycle is missing",
    ),
    RequiredPatternRule(
        "declarative-frame-filter-handlers",
        "backend/app/processing/frame_filter_handlers.py",
        r"_NUMPY_FILTER_HANDLERS\s*:[\s\S]*[\"']anime_cleanup[\"'][\s\S]*_TENSOR_FILTER_HANDLERS\s*:[\s\S]*FILTER_KINDS\s*=\s*frozenset",
        "declarative frame-filter handler maps are missing",
    ),
    RequiredPatternRule(
        "shared-decoded-frame-writer-thread",
        "backend/app/processing/streaming/worker_process_io.py",
        r"class\s+DecodedFrameWriterConfig\b[\s\S]*def\s+start_decoded_frame_writer\b[\s\S]*target=_write_decoded_frames_to_worker",
        "shared decoded-frame writer thread helper is missing",
    ),
    RequiredPatternRule(
        "primary-video-dimensions-helper",
        "backend/app/utils/ffmpeg/media_probe.py",
        r"def\s+get_primary_video_dimensions\b",
        "primary video dimension helper is missing",
    ),
    RequiredPatternRule(
        "shared-benchmark-threshold-comparator",
        "backend/app/benchmark/comparison.py",
        r"def\s+_compare_threshold\b[\s\S]*direction:\s*_ThresholdDirection",
        "shared benchmark threshold comparator is missing",
    ),
    RequiredPatternRule(
        "shared-paddlegan-chunk-trace",
        "backend/app/algorithms/paddle/paddlegan_vsr/runner.py",
        r"def\s+_record_chunk_trace\b[\s\S]*trace_chunks\.append",
        "shared PaddleGAN chunk trace helper is missing",
    ),
    RequiredPatternRule(
        "typed-environment-protocol",
        "frontend/src-tauri/src/models/env.rs",
        r"string_enum!\(AlgorithmFamily\b[\s\S]*string_enum!\(EnvironmentCheckSource\b[\s\S]*string_enum!\(InferenceEngine\b[\s\S]*string_enum!\(InputFrameMode\b[\s\S]*pub(?:\s*\([^)]*\))?\s+enum\s+RuntimeMode\b",
        "strongly typed Rust environment protocol is missing",
    ),
    RequiredPatternRule(
        "environment-cache-schema-12",
        "frontend/src-tauri/src/persistence/storage.rs",
        r"ENVIRONMENT_CACHE_SCHEMA_VERSION:\s*u32\s*=\s*12\s*;",
        "environment cache schema 12 is missing",
    ),
    RequiredPatternRule(
        "runtime-config-model-projection",
        "backend/app/cli/runtime_configs.py",
        r"def\s+json_section\b[\s\S]*def\s+json_sections\b[\s\S]*def\s+with_workflow\b",
        "RuntimeConfigs model projection API is missing",
    ),
    RequiredPatternRule(
        "windows-rust-clippy-gate",
        ".github/workflows/test.yml",
        r"cargo\s+clippy\s+--all-targets\s+--\s+-D\s+warnings",
        "Windows Rust Clippy CI gate is missing",
    ),
    RequiredPatternRule(
        "linux-rust-clippy-gate",
        ".github/workflows/test-arc.yml",
        r"cargo\s+clippy\s+--all-targets\s+--\s+-D\s+warnings",
        "Linux Rust Clippy CI gate is missing",
    ),
    RequiredPatternRule(
        "rust-anime-cleanup-filter-kind",
        "frontend/src-tauri/src/models/config.rs",
        r"\bAnimeCleanup\b",
        "Rust anime_cleanup filter kind is missing",
    ),
    RequiredPatternRule(
        "python-anime-cleanup-filter-kind",
        "backend/app/models/__init__.py",
        r"Literal\[[^\]]*[\"']anime_cleanup[\"']",
        "Python anime_cleanup filter kind is missing",
    ),
    RequiredPatternRule(
        "frontend-anime-cleanup-catalog",
        "frontend/src/services/filters/filter-catalog.ts",
        r"kind:\s*[\"']anime_cleanup[\"']",
        "frontend anime_cleanup filter catalog entry is missing",
    ),
    RequiredPatternRule(
        "backend-anime-cleanup-runtime",
        "backend/app/processing/frame_filter_handlers.py",
        r"def\s+_apply_numpy_anime_cleanup\b[\s\S]*?\bapply_anime_cleanup\s*\(",
        "backend anime_cleanup frame filter dispatch is missing",
    ),
    RequiredPatternRule(
        "ipc-command-keyof",
        "frontend/src/lib/ipc/contract.ts",
        r"\bexport\s+type\s+IpcCommand\s*=\s*keyof\s+IpcCommandArgs\b",
        "IPC command keyof source is missing",
    ),
    RequiredPatternRule(
        "pydantic-model-camel-alias",
        "backend/app/models/__init__.py",
        r"from\s+pydantic\.alias_generators\s+import\s+to_camel",
        "Pydantic camel alias must use library helper",
    ),
    RequiredPatternRule(
        "pydantic-payload-camel-alias",
        "backend/app/protocol/payloads.py",
        r"from\s+pydantic\.alias_generators\s+import\s+to_camel",
        "payload camel alias must use library helper",
    ),
    RequiredPatternRule(
        "typed-ndjson-errors",
        "backend/app/__main__.py",
        r"def\s+_emit_typed_error\b[\s\S]*emitter\.error\s*\([\s\S]*def\s+_emit_unhandled_exception\b[\s\S]*_emit_error_payload\s*\(",
        "normal and bootstrap CLI failures must use shared error emitters",
    ),
    RequiredPatternRule(
        "private-ndjson-emitter",
        "backend/app/protocol/__init__.py",
        r"\bclass\s+_NdjsonEmitter\b",
        "private NDJSON emitter is missing",
    ),
    RequiredPatternRule(
        "shared-stage-route-component",
        "frontend/src/router/index.ts",
        r"const\s+StageModuleView\s*=.*StageModuleView\.vue[\s\S]*preprocess:\s*\{\s*component:\s*StageModuleView,\s*props:\s*\{\s*stage:\s*['\"]preprocess['\"]\s*\}\s*\}[\s\S]*postprocess:\s*\{\s*component:\s*StageModuleView,\s*props:\s*\{\s*stage:\s*['\"]postprocess['\"]\s*\}\s*\}",
        "preprocess and postprocess routes must share StageModuleView",
    ),
    RequiredPatternRule(
        "ffmpeg-media-probe-boundary",
        "backend/app/utils/ffmpeg/media_probe.py",
        r"def\s+get_video_info\b[\s\S]*def\s+get_frame_count\b[\s\S]*def\s+is_available\b",
        "FFmpeg media probe boundary is missing",
    ),
    RequiredPatternRule(
        "ffmpeg-capability-probe-boundary",
        "backend/app/utils/ffmpeg/capability_probe.py",
        r"def\s+parse_codec_profile\b[\s\S]*def\s+probe_rate_control_modes\b[\s\S]*def\s+probe_decoder_hardware_devices\b",
        "FFmpeg capability probe boundary is missing",
    ),
    RequiredPatternRule(
        "ffmpeg-capability-aggregation-boundary",
        "backend/app/utils/ffmpeg/capabilities.py",
        r"def\s+discover_capabilities\b",
        "FFmpeg capability aggregation boundary is missing",
    ),
    RequiredPatternRule(
        "ruff-unused-argument-gate",
        "ruff.toml",
        r"select\s*=\s*\[[^\]]*['\"]ARG['\"]",
        "Ruff ARG production gate is missing",
    ),
    RequiredPatternRule(
        "benchmark-default-scenario-ssot",
        "backend/app/cli/parser.py",
        r"from\s+app\.benchmark\.runner\s+import\s+DEFAULT_SCENARIO[\s\S]*default\s*=\s*DEFAULT_SCENARIO",
        "benchmark parser must reuse DEFAULT_SCENARIO",
    ),
)


REFERENCE_RULES = (
    ForbiddenReferenceRule(
        "obsolete-decode-form-aggregator-reference",
        roots=("frontend/src", "frontend/tests"),
        patterns=(r"composables/forms/decode-form-bindings",),
        message="obsolete Decode form aggregator reference",
        suffixes=(".ts", ".vue"),
    ),
    ForbiddenReferenceRule(
        "obsolete-stage-file-rules-reference",
        roots=("backend/app", "backend/tests"),
        patterns=(r"app\.processing\.streaming\.stage_file_rules\b",),
        message="obsolete stage-file rules module reference",
        suffixes=(".py",),
        excludes=("backend/tests/test_architecture_contract_rule_engine.py",),
    ),
    ForbiddenReferenceRule(
        "obsolete-frontend-environment-protocol",
        roots=("frontend/src", "frontend/tests"),
        patterns=(
            r"types/domain/(?:env|capability|workflow)",
            r"services/env/normalize",
            r"\bnormalizeCheckPayload\b",
            r"\b(?:backendDeviceSupport|sequenceMode|lastCheckedAt|deviceType|driverVersion|adapterCompatibility)\b",
        ),
        message="obsolete frontend environment protocol reference",
        suffixes=(".ts", ".tsx", ".vue"),
    ),
    ForbiddenReferenceRule(
        "legacy-task-commands",
        roots=("README.md", "docs"),
        patterns=(r"\bpause_task\b", r"\bresume_task\b"),
        message="legacy task command reference",
        suffixes=(".md",),
    ),
    ForbiddenReferenceRule(
        "obsolete-streaming-imports",
        roots=("backend/app", "backend/tests"),
        patterns=(
            r"app\.processing\.streaming\.(?:decoder|processor(?:\b|_)|pipeline_raw_(?:runtime|state|stage|completion)|worker_pipeline_queue|stage_file_chunk_progress)\b",
            r"app\.processing\.streaming\._tensor_chain\b",
        ),
        message="obsolete streaming module reference",
        suffixes=(".py",),
        excludes=("backend/tests/test_architecture_contracts.py",),
    ),
    ForbiddenReferenceRule(
        "obsolete-frontend-binding-imports",
        roots=("frontend/src",),
        patterns=(
            r"enhance-field-bindings",
            r"encode-output-bindings",
            r"enhance-option-bindings",
            r"@/lib/ipc(?:['\"]|/index)",
        ),
        message="obsolete frontend facade reference",
        suffixes=(".ts", ".tsx", ".vue"),
    ),
    ForbiddenReferenceRule(
        "positional-workbench-module-access",
        roots=("frontend/src",),
        patterns=(r"\bWORKBENCH_MODULES\s*\[\s*\d+\s*\]", r"\bWORKBENCH_MODULE_KEYS\b"),
        message="positional or duplicate workbench module registry",
        suffixes=(".ts", ".tsx", ".vue"),
    ),
    _forbid(
        "hardcoded-workbench-module-route",
        "frontend/src/router/index.ts",
        r"\b(?:path|redirect)\s*:\s*[\"']/(?:home|input|decode|preprocess|enhance|postprocess|encode|render)[\"']",
        "workbench module path duplicated in router",
    ),
    ForbiddenReferenceRule(
        "obsolete-ffmpeg-probe-imports",
        roots=("backend/app", "backend/tests"),
        patterns=(r"app\.utils\.ffmpeg\.probe\b", r"from\s+\.\s+import\s+probe\b"),
        message="obsolete monolithic FFmpeg probe import",
        suffixes=(".py",),
        excludes=(
            "backend/tests/test_architecture_contracts.py",
            "backend/tests/test_architecture_contract_rule_engine.py",
        ),
    ),
    ForbiddenReferenceRule(
        "removed-super-resolution-auto-download",
        roots=("backend/app", "frontend/src"),
        patterns=(r"\bautoDownloadWeights\b", r"\bauto_download_weights\b", r"\bauto_download\b"),
        message="removed super-resolution auto-download reference",
        suffixes=(".py", ".ts", ".tsx", ".vue"),
    ),
    ForbiddenReferenceRule(
        "obsolete-anime-module-references",
        roots=(
            "backend/app",
            "frontend/src",
            "frontend/src-tauri/src",
            "frontend/tests/e2e",
            "README.md",
            "docs/01-architecture-overview.md",
        ),
        patterns=(
            r"\banime_optimization\b",
            r"\bAnimeConfig\b",
            r"\bworkflow\.anime\b",
            r"动漫优化",
        ),
        message="obsolete standalone anime module reference",
        suffixes=(".py", ".ts", ".tsx", ".vue", ".rs", ".md"),
        excludes=("backend/tests/test_architecture_contracts.py",),
    ),
    ForbiddenReferenceRule(
        "obsolete-e2e-environment-fields",
        roots=("frontend/tests/e2e",),
        patterns=(
            r"result\.result\.(?:type|tensorBackends|onnxRuntime|rifeModel|resources|runtime|animeProfiles)\b",
            r"\bffmpeg\.toHaveProperty\([\"'](?:version|path|ffprobePath)[\"']",
            r"\bgpu\.toHaveProperty\([\"'](?:available|devices)[\"']",
        ),
        message="obsolete E2E environment field reference",
        suffixes=(".ts",),
    ),
    ForbiddenReferenceRule(
        "obsolete-frontend-video-info-fields",
        roots=("frontend/tests",),
        patterns=(
            r"\btype\s*:\s*[\"']info[\"']",
            r"\bhasAudio\s*:",
            r"\b(?:frames|duration)\s*:\s*\d",
        ),
        message="obsolete frontend VideoInfo field reference",
        suffixes=(".ts", ".tsx"),
    ),
    ForbiddenReferenceRule(
        "planning-test-private-aliases",
        roots=("backend/tests",),
        patterns=(
            r"from\s+app\.planning\s+import[\s\S]*?\bas\s+_resolve_(?:expected_output_frames|processing_steps)\b",
        ),
        message="planning test private alias",
        suffixes=(".py",),
        excludes=("backend/tests/test_architecture_contracts.py",),
    ),
    ForbiddenReferenceRule(
        "pipeline-test-private-aliases",
        roots=("backend/tests/test_processing",),
        patterns=(
            r"from\s+app\.processing\.streaming\.pipeline\s+import\s+[^\n]*\b_[A-Za-z0-9_]+\b",
            r"from\s+app\.processing\.streaming\.pipeline\s+import\s*\([\s\S]*?\b_[A-Za-z0-9_]+\b[\s\S]*?\)",
        ),
        message="pipeline test private alias",
        suffixes=(".py",),
    ),
    ForbiddenReferenceRule(
        "obsolete-model-metrics-imports",
        roots=("frontend/src",),
        patterns=(r"from\s+['\"](?:@/services|\.{1,2})/model-metrics['\"]",),
        message="obsolete model metrics barrel import",
        suffixes=(".ts", ".tsx", ".vue"),
    ),
    ForbiddenReferenceRule(
        "obsolete-decode-queue-references",
        roots=("backend/app", "backend/tests", "docs", "README.md"),
        patterns=(
            r"\bdecoder_worker\b",
            r"\bprocessor_worker\b",
            r"\bDecodedFrame\b",
            r"\b_DECODE_END\b",
            r"\bdecode_queue\b",
        ),
        message="obsolete decode queue reference",
        suffixes=(".py", ".md", ".rst", ".txt"),
        excludes=(
            "backend/tests/test_architecture_contracts.py",
            "backend/tests/test_architecture_contract_rule_engine.py",
        ),
    ),
)


RULES = (*ABSENT_PATH_RULES, *FORBIDDEN_PATTERN_RULES, *REQUIRED_PATTERN_RULES, *REFERENCE_RULES)
